apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-service
    spec:
      containers:
        - name: hello-world-service
          image: registry.cicd.siriuscloudservices.com/library/hello-world-service
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30