apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          image: registry.api.cicd.siriuscloudservices.com/library/{{SERVICE_NAME}}
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30
      imagePullSecrets:
        - name: regsecret

