apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{SERVICE_NAME}}
spec:
  rules:
  - host: {{SERVICE_NAME}}.api.cicd.aagsiriuscom.com
    http:
      paths:
      - backend:
          serviceName: {{SERVICE_NAME}}
          servicePort: 8080
