apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{SERVICE_NAME}}
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  namespaceSelector:
    matchNames:
    - "{{SERVICE_NAME}}"
  endpoints:
  - port: http
    path: /prometheus