apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-world-service
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: hello-world-service
  namespaceSelector:
    matchNames:
    - "hello-world-service"
  endpoints:
  - port: http
    path: /prometheus