apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  labels:
    app: {{SERVICE_NAME}}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: {{SERVICE_NAME}}
